export const route = [
    {
        component: 'Home',
        type: 'tab',
        tab: null,
        icon: 'home',
    },
    {
        component: 'Dashboard',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Register',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Approve',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Attendance',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Paycheck',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'News',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'GPS',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Survey',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Meeting',
        type: 'stack',
        tab: 'Home',
        icon: '',
    },
    {
        component: 'Phonebook',
        type: 'tab',
        tab: '',
        icon: 'address-book',
    },
    {
        component: 'PhonebookDetail',
        type: 'stack',
        tab: 'Phonebook',
        icon: '',
    },
    {
        component: 'QR',
        type: 'tab',
        tab: '',
        icon: 'qrcode',
    },
    {
        component: 'QRDetail',
        type: 'stack',
        tab: 'QR',
        icon: '',
    },
    {
        component: 'Notification',
        type: 'tab',
        tab: '',
        icon: 'bell',
    },
    {
        component: 'NotificationDetail',
        type: 'stack',
        tab: 'Notification',
        icon: '',
    },
    {
        component: 'User',
        type: 'tab',
        tab: '',
        icon: 'user-alt',
    },
    {
        component: 'UserDetail',
        type: 'stack',
        tab: 'User',
        icon: '',
    },
]